name: MLflow Training CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  training-model:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Install MLflow
        shell: bash -el {0}
        run: pip install mlflow

      - name: Jalankan MLflow Project
        shell: bash -el {0}
        run: mlflow run MLProject/